dist: bionic
language: python
python:
- 3.8
env:
  matrix:
    secure: nztQ3Xr6MmVOXEEA7i7TBz7tXaLzU5QvW1XUG8POpbLECB/RqUuwMbaSeX1gWvATefRh9OKxrk5Ba5saD9rF5jcLKaX52DHbZa9O5xpIOjmNMSftQ8MMi+MG+zT71zH9G9gr6yce8PDt902FL6HpIm4wdrzu2VfQuXcUdg9a7bz1vzp1FD7kbkgwn+GgMx6Vi9n5ZibVvXwPeP4iS0BIY5AJdcUHYXqQtvDMmQ0cx2vBrfi0JHqjQkUZJTf+txJNs6uOREw4qpjVqK0sal034ky5SXB43r+gLi7OREGjvNtdiXc8srwASvv2CIcWCRGEmuDnd14me1KRKV9ORcawDZcPvQlvpZAPok8NrbPxh3ODqSgRVKzOUNIK2lErqAh18IP+kM6yGuD3M/sRbgKgzWwbG+Gp0l7Q5hCDLSA6LKPIR1IO0S2HnBBQgUz+Fc4oSjM34j9Xv23kJ4EOBPXjy0MMDeHMgOJZbLuQiFTSltHg++iy5sB9GaKjDY/JG2nYHVfyRaBEz6N0RnCEKhBxzaxepUAZSDnvNuwFAnAXhWMDE2BSbxtVTHfm+5dsVzg+jIuQjcI1LU22dJd3WykNG1qgvvEEGcR27vgPB+qMRXermVRhP+2KYmthof5zw1MRykiogfVFID48iWLRSPkYx2reutviGkGZtRx0Mlxz+qw=
before_install:
- chmod +x ./.deploy_scripts/tlsetup.sh
- "./.deploy_scripts/tlsetup.sh"
install:
- pip install -r requirements.txt
script:
- make deploy
- make pdf
after_success:
- cp ./_build/latex/Images_from_above.pdf ./_build/html/Images_from_above.pdf
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GH_TOKEN"
  keep-history: false
  on:
    branch: main
  local_dir: _build/html
